name: denuanime
description: "An anime companion application"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter_native_splash: ^2.4.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # FONTS
  fonts:
    - family: "Montserrat"
      fonts:
        - asset: fonts/montserrat_variable_italic.ttf
        - asset: fonts/montserrat_variable_normal.ttf
  # ASSETS
  assets:
    - assets/splash_full.png
    - assets/splash_branding.png
    - assets/splash_logo_only.png
    - assets/full.png
    - assets/icons/ic_facebook.png
    - assets/icons/ic_google.png
# ICONS
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash_logo_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/splash_logo_icon.png"
    background_color: "#000"
    theme_color: "#fff"
  windows:
    generate: true
    image_path: "assets/splash_logo_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/splash_logo_icon.png"
