// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGbdHNu8iUOLGuYSmx_pt9KFUE0y9aqc0',
    appId: '1:721223882849:web:d1baa073c9cc0647523220',
    messagingSenderId: '721223882849',
    projectId: 'denu-anime',
    authDomain: 'denu-anime.firebaseapp.com',
    storageBucket: 'denu-anime.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvfC-RgWhl10IBMpXvzsDL5zo3-rqbCfs',
    appId: '1:721223882849:android:02611c9d1124cc1f523220',
    messagingSenderId: '721223882849',
    projectId: 'denu-anime',
    storageBucket: 'denu-anime.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUzUn8JiN6ZSba0yQTFCGkeWfhh7mSOTU',
    appId: '1:721223882849:ios:dbfe87c9a419ac54523220',
    messagingSenderId: '721223882849',
    projectId: 'denu-anime',
    storageBucket: 'denu-anime.firebasestorage.app',
    iosBundleId: 'com.example.denuanime',
  );
}
